[pytest]
testpaths = tests
addopts = --strict-config --strict-markers
filterwarnings =
    error
    ignore:^SelectableGroups dict interface is deprecated\. Use select\.$:DeprecationWarning
    ignore:^BaseAgentConfig is deprecated and will be removed in future versions\..*$:DeprecationWarning
